# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anceator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('secound_name', models.CharField(blank=True, max_length=24, null=True)),
                ('surname', models.CharField(max_length=36)),
                ('maiden_name', models.CharField(blank=True, max_length=36, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/content/')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.IntegerField(choices=[(-1, 'nie określono'), (0, 'rodzic'), (1, 'dziecko'), (2, 'rodzeństwo'), (3, 'w związku')], default=-1)),
                ('anceator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anceator1', to='genealogy_app.Anceator')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anceator2', to='genealogy_app.Anceator')),
            ],
        ),
        migrations.AddField(
            model_name='anceator',
            name='family',
            field=models.ManyToManyField(through='genealogy_app.Relationship', to='genealogy_app.Anceator'),
        ),
    ]
