# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anceator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/content/'),
        ),
        migrations.AddField(
            model_name='anceator',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
