# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy_app', '0002_anceator_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anceator',
            name='dead_or_alive',
            field=models.IntegerField(choices=[(-1, 'nie określono'), (0, 'żyje'), (1, 'nie żyje')], default=-1),
        ),
        migrations.AddField(
            model_name='anceator',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anceator',
            name='gender',
            field=models.IntegerField(choices=[(-1, 'nie określono'), (0, 'kobieta'), (1, 'mężczyzna')], default=-1),
        ),
    ]
