# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy_app', '0004_auto_20170318_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='anceator',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='family',
        ),
        migrations.RemoveField(
            model_name='anceator',
            name='family',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.AddField(
            model_name='anceator',
            name='family',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='genealogy_app.Family'),
        ),
    ]
